version: '3.7'

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bot_db
    depends_on:
      - db_bot
    restart: on-failure
    command: python start_app.py

  db_bot:
    container_name: db_bot
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 'Admin'
      POSTGRES_PASSWORD: 'Admin123'
      POSTGRES_DB: 'BASE_FOR_TELEG_BOT'
    ports:
      - '5432:5432'
    networks:
      - bot_db
    volumes:
      - db_bot_vol:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: on-failure
    networks:
      - bot_db
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

networks:
  bot_db:

volumes:
  redis:
  db_bot_vol: